server:
  port: 9000

spring:
  application:
    name: GATEWAY-SERVICE
  profiles:
    active: gateway,server
  config:
    import:
      - "optional:configserver:http://localhost:9009"
frontEnd:
  url: "http://localhost:5173"